### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by brudnak** [GoesToEleven/golang-project#115]
# Branch Suggestion 🕊️ 🌅  

Suggesting the master branch of this repository be renamed to main. Should be an easy fix to the course outline as well with find and replace.

**Comment by oralordos** [comment]
@GoesToEleven will need to do this, since he's the one who can change the default branch on Github. [Here is a guide.](https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main)

**Comment by temp-todd-mcleod** [comment]
I'm confused by this. Do you need me to do something?

**Comment by brudnak** [comment]
@GoesToEleven following the instructions that @oralordos linked to would work. However, it might not be feasible since the new naming conventions wouldn't sync up with recorded videos. I was initially just thinking in terms of the course outline. So this probably can't be done yet, but an idea for the future 😃 😃 😃
